### ISSUE TITLE
LX - "Mount Error: Device not found" while in USB Boot Mode

### ISSUE THREAD

**Issue by tetrisxz** [jrspruitt/OpenLFConnect#3]
Hello!

I'm trying to boot Surgeon on my LX, however when I do so I get the following error:
"Pager Error: Mount Error: Device not found."
If anyone can help me out with this, that would be great.

Thank you!

**Comment by jrspruitt** [comment]
If it's not an issue with the device itself, I would assume the way the OS system does thing, has changed. When I stopped maintaining it, I was already having trouble with OS's changing things.

**Comment by tetrisxz** [comment]
I see. I'm currently running on Windows 10, so that may be what causes it.

Thanks for the help!
