### ISSUE TITLE
Factory reset didj?

### ISSUE THREAD

**Issue by RiceboySleeps** [jrspruitt/OpenLFConnect#4]
I'm attempting to factory reset my didj. I was able to mount it, but when I enter didj_update_firmware, OpenLFConnect says that I'm missing erootfs kernel. What is that? I have the firmware file (DIDJ-0x000E0003-000001.lfp from the offline Didj LFConnect installer) saved in files/Didj, but I'm not sure how to get the program to use it.

I then tried didj_update_firmware didj/DIDJ-0x000E0003-000001.lfp (since I put the .lfp file in the Files/Didj folder), but I got another error message that says "Didj Error: Path is not a directory."

Thanks so much for your time 😊

**Comment by RiceboySleeps** [comment]
I then tried didj_update_firmware didj/DIDJ-0x000E0003-000001.lfp (since I put the .lfp file in the Files/Didj folder), but I got another error message that says "Didj Error: Path is not a directory."

**Comment by RiceboySleeps** [comment]
Okay, I was able to update the firmware! (I unzipped the .lfp file and moved the firmware-LF_LF1000 folder to the "files" folder. I'll leave this here just in case it might be helpful for someone in the future.

**Comment by RiceboySleeps** [comment]
PS - Thank you for making this amazing program, @jrspruitt! You're awesome.

**Comment by RiceboySleeps** [comment]
Hm. It seems that my Didj wasn't actually reset. Is there something I'm missing? I've updated the firmware and the bootloader, and I deleted the profile folders, but the game that I'm playing is still displaying the same piece of data that it did on previous accounts. There must be some setting somewhere that's persisting. If anyone has any suggestions, I'd really appreciate it!

**Comment by jrspruitt** [comment]
Hello, I'm sorry but I haven't worked on this in many years, and am really not sure what is going on. There are some discord servers around that might be of help.

-Jason

**Comment by RiceboySleeps** [comment]
No problem, Jason. I just found the server and am going to try asking there.
